swagger: '2.0'
info:
  title: Users management API
  version: '1.0'
host: api.server.test
basePath: /api/photoapp/v1/
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: User
paths:
  /users:
    get:
      operationId: getUsers
      summary: Get list of users
      tags:
        - User
      parameters:
        - name: count
          in: query
          description: count of users to be returned in response
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema: 
            type: array
            items: 
              $ref: '#/definitions/UserRef'
        '400': 
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: server error
          schema:
            $ref: '#/definitions/Error'
    post:
      operationId: createUsers
      summary: 'Create users'
      tags:
        - User
      parameters: 
        - name: users
          description: Users to be created
          required: true
          in: body
          schema:
            $ref: '#/definitions/UserRef'
      responses:
        '201':
          description: Created
          schema:
            $ref: '#/definitions/UserRef'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'

definitions:
  UserRef:
    type: object
    description: User details
    required:
      - firstName
      - lastName
    properties: 
      id:
        type: string
        description: Customer ID
      firstName:
        type: string
        description: Customer first name
      lastName:
        type: string
        description: Customer last name
  Error:
    type: object
    description: Error details
    properties: 
      code:
        type: string
        description: Error code
      reason:
        type: string
        description: Error reason
      message:
        type: string
        description: Error message

    